### ISSUE TITLE
`includePaths`, mentioned in README, doesn’t seem to have any effect

### ISSUE THREAD

**Issue by alanhogan** [sass-eyeglass/broccoli-eyeglass#13]
Please see the folders `example-3` and `shared-sass-files`, here: https://github.com/alanhogan/broccoli-eyeglass/tree/examples-with-includePath/examples

EXPECTED: Running `broccoli build dist` from `example-3` should build application.css successfully

ACTUAL: Build fails because `font-stacks` cannot be `@import`-ed.

Note the [Brocfile.js](https://github.com/alanhogan/broccoli-eyeglass/blob/examples-with-includePath/examples/example-3/Brocfile.js) passes an `includePaths` option that should fix this, but it doesn’t.

Error message:

```
examples/example-3[examples-with-includePath]% broccoli build dist
/Users/ahogan/Repos/broccoli-eyeglass/examples/example-3/node_modules/broccoli-eyeglass/node_modules/rsvp/dist/rsvp.js:1532
        throw reason;
              ^
Error: Could not import font-stacks from any of the following locations: /Users/ahogan/Repos/broccoli-eyeglass/examples/example-3/src/font-stacks.scss, /Users/ahogan/Repos/broccoli-eyeglass/examples/example-3/src/font-stacks/index.scss, /Users/ahogan/Repos/broccoli-eyeglass/examples/example-3/src/font-stacks.sass, /Users/ahogan/Repos/broccoli-eyeglass/examples/example-3/src/font-stacks/index.sass, /Users/ahogan/Repos/broccoli-eyeglass/examples/example-3/src/font-stacks.css, /Users/ahogan/Repos/broccoli-eyeglass/examples/example-3/src/font-stacks/index.css, /Users/ahogan/Repos/broccoli-eyeglass/examples/example-3/src/_font-stacks.scss, /Users/ahogan/Repos/broccoli-eyeglass/examples/example-3/src/font-stacks/_index.scss, /Users/ahogan/Repos/broccoli-eyeglass/examples/example-3/src/_font-stacks.sass, /Users/ahogan/Repos/broccoli-eyeglass/examples/example-3/src/font-stacks/_index.sass, /Users/ahogan/Repos/broccoli-eyeglass/examples/example-3/src/_font-stacks.css, /Users/ahogan/Repos/broccoli-eyeglass/examples/example-3/src/font-stacks/_index.css, /Users/ahogan/Repos/broccoli-eyeglass/examples/example-3/src/index.scss, /Users/ahogan/Repos/broccoli-eyeglass/examples/example-3/src/index.sass, /Users/ahogan/Repos/broccoli-eyeglass/examples/example-3/src/index.css, /Users/ahogan/Repos/broccoli-eyeglass/examples/example-3/src/_index.scss, /Users/ahogan/Repos/broccoli-eyeglass/examples/example-3/src/_index.sass, /Users/ahogan/Repos/broccoli-eyeglass/examples/example-3/src/_index.css, /Users/ahogan/Repos/broccoli-eyeglass/examples/example-3/src/font-stacks.scss, /Users/ahogan/Repos/broccoli-eyeglass/examples/example-3/src/font-stacks.sass, /Users/ahogan/Repos/broccoli-eyeglass/examples/example-3/src/font-stacks.css, /Users/ahogan/Repos/broccoli-eyeglass/examples/example-3/src/_font-stacks.scss, /Users/ahogan/Repos/broccoli-eyeglass/examples/example-3/src/_font-stacks.sass, /Users/ahogan/Repos/broccoli-eyeglass/examples/example-3/src/_font-stacks.css
    at /Users/ahogan/Repos/broccoli-eyeglass/examples/example-3/src/application.scss:1:9
    at /Users/ahogan/Repos/broccoli-eyeglass/examples/example-3/node_modules/broccoli-eyeglass/lib/broccoli_sass_compiler.js:282:20
    at Object.finallyHandler (/Users/ahogan/Repos/broccoli-eyeglass/examples/example-3/node_modules/broccoli-eyeglass/node_modules/chained-emitter/node_modules/bluebird/js/main/finally.js:39:23)
    at Object.tryCatcher (/Users/ahogan/Repos/broccoli-eyeglass/examples/example-3/node_modules/broccoli-eyeglass/node_modules/chained-emitter/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/ahogan/Repos/broccoli-eyeglass/examples/example-3/node_modules/broccoli-eyeglass/node_modules/chained-emitter/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/Users/ahogan/Repos/broccoli-eyeglass/examples/example-3/node_modules/broccoli-eyeglass/node_modules/chained-emitter/node_modules/bluebird/js/main/promise.js:577:18)
    at Promise._settlePromises (/Users/ahogan/Repos/broccoli-eyeglass/examples/example-3/node_modules/broccoli-eyeglass/node_modules/chained-emitter/node_modules/bluebird/js/main/promise.js:693:14)
    at Async._drainQueue (/Users/ahogan/Repos/broccoli-eyeglass/examples/example-3/node_modules/broccoli-eyeglass/node_modules/chained-emitter/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/Users/ahogan/Repos/broccoli-eyeglass/examples/example-3/node_modules/broccoli-eyeglass/node_modules/chained-emitter/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/ahogan/Repos/broccoli-eyeglass/examples/example-3/node_modules/broccoli-eyeglass/node_modules/chained-emitter/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
```

With line breaks, that’s

> Error: Could not import font-stacks from any of the following locations: /Users/ahogan/Repos/broccoli-eyeglass/examples/example-3/src/font-stacks.scss
/Users/ahogan/Repos/broccoli-eyeglass/examples/example-3/src/font-stacks/index.scss
/Users/ahogan/Repos/broccoli-eyeglass/examples/example-3/src/font-stacks.sass
/Users/ahogan/Repos/broccoli-eyeglass/examples/example-3/src/font-stacks/index.sass
/Users/ahogan/Repos/broccoli-eyeglass/examples/example-3/src/font-stacks.css
/Users/ahogan/Repos/broccoli-eyeglass/examples/example-3/src/font-stacks/index.css
/Users/ahogan/Repos/broccoli-eyeglass/examples/example-3/src/_font-stacks.scss
/Users/ahogan/Repos/broccoli-eyeglass/examples/example-3/src/font-stacks/_index.scss
/Users/ahogan/Repos/broccoli-eyeglass/examples/example-3/src/_font-stacks.sass
/Users/ahogan/Repos/broccoli-eyeglass/examples/example-3/src/font-stacks/_index.sass
/Users/ahogan/Repos/broccoli-eyeglass/examples/example-3/src/_font-stacks.css
/Users/ahogan/Repos/broccoli-eyeglass/examples/example-3/src/font-stacks/_index.css
/Users/ahogan/Repos/broccoli-eyeglass/examples/example-3/src/index.scss
/Users/ahogan/Repos/broccoli-eyeglass/examples/example-3/src/index.sass
/Users/ahogan/Repos/broccoli-eyeglass/examples/example-3/src/index.css
/Users/ahogan/Repos/broccoli-eyeglass/examples/example-3/src/_index.scss
/Users/ahogan/Repos/broccoli-eyeglass/examples/example-3/src/_index.sass
/Users/ahogan/Repos/broccoli-eyeglass/examples/example-3/src/_index.css
/Users/ahogan/Repos/broccoli-eyeglass/examples/example-3/src/font-stacks.scss
/Users/ahogan/Repos/broccoli-eyeglass/examples/example-3/src/font-stacks.sass
/Users/ahogan/Repos/broccoli-eyeglass/examples/example-3/src/font-stacks.css
/Users/ahogan/Repos/broccoli-eyeglass/examples/example-3/src/_font-stacks.scss
/Users/ahogan/Repos/broccoli-eyeglass/examples/example-3/src/_font-stacks.sass
/Users/ahogan/Repos/broccoli-eyeglass/examples/example-3/src/_font-stacks.css

**Note that `shared-sass-files` doesn’t appear anywhere in the list of places Sass looked for `font-stacks`.**

I plan on trying to debug this next week (depending on what my team prefers me to work on).

**Comment by alanhogan** [comment]
I figured out the problem (in `eyeglass`) and will be making a patch tomorrow.

**Comment by alanhogan** [comment]
I figure we can close this issue when Eyeglass is patched (boy, does that sound piratey) and when sass-eyeglass’ dependency is updated

**Comment by alanhogan** [comment]
@chriseppstein Think we could slap a new version number on eyeglass & bump the dependency here in broccoli-eyeglass to solve this issue? :)

**Comment by chriseppstein** [comment]
we released since then :)
