### ISSUE TITLE
How would a broccoli-eyeglass user register assets?

### ISSUE THREAD

**Issue by alanhogan** [sass-eyeglass/broccoli-eyeglass#7]
From sass-eyeglass/eyeglass:

> Eyeglass provides core support for exposing assets to your stylesheets for your application or from an eyeglass module and generating urls to those assets as well as making sure only those assets that you actually use end up in your built application. … **The `addSource` method on `eyeglass.assets` is how you add assets to your application.**

The broccoli-eyeglass source doesn’t seem to include any references to `assets` or `addSource`. I’m new to Broccoli and while I get at least the basics of 'trees', I’m having a hard time understanding how to map this concept to the above instructions (or to the old Compass pattern of referring to an images directory, for that matter).

Motivation: Trying to get image spriting to work in a broccoli-eyeglass environment!

**Comment by eoneill** [comment]
@alanhogan did you figure this out?

If not, @chriseppstein do we have a recommended way to do this?

**Comment by alanhogan** [comment]
I haven't figured out an answer to this question as asked, no, but I worked around it (at least for now) by changing the directory I was passing in so that it contained both my images and stylesheets.

**Comment by chriseppstein** [comment]
In eyeglass 0.8 you can register assets via options hash. Before that, the way was a lot more complicated, and not really worth documenting here :P
